-- Base y tablas para Gestión de Cheques
CREATE DATABASE IF NOT EXISTS db_gdc
  CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE db_gdc;

CREATE TABLE IF NOT EXISTS cheques (
  id INT AUTO_INCREMENT PRIMARY KEY,
  proveedor VARCHAR(180) NOT NULL,
  fecha_pago DATE NOT NULL,
  monto DECIMAL(15,2) NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS view_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token CHAR(64) NOT NULL UNIQUE,
  filtros_json JSON NULL,
  expira_en DATETIME NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
